services:

  # Zafiyetli Web Paneli
  web_panel:
    build: ./web_panel
    ports:
      - "5000:5000"
    volumes:
      - ./web_panel:/app
    environment:
      SQL_INJECTION_ENABLED: "false"
      WEBPANEL_LOCK_ENABLED: "false"
      RANSOMWARE_ENABLED:    "true"    # Ransomware zafiyeti
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Zafiyetli Araç Kontrol Servisi
  vehicle_controller:
    build: ./vehicle_controller
    ports:
      - "2222:22"    # SSH — ransomware saldırısı
    container_name: vehicle_controller
    environment:
      SSH_ENABLED: "false"
      SPEED_SPOOF_ENABLED: "false"
      IOT_SENSOR_ENABLED: "false"
      IDS_FALSE_ALARM_ENABLED: "false"
      IDS_TIMING_ENABLED: "false"
      FAKE_VEHICLE_ENABLED: "false"
      V2V_ENABLED: "false"
      V2I_ENABLED: "true"
    extra_hosts:
      - "host.docker.internal:host-gateway"
